export function getData() {
  const data = [
    {
      product: "Maria Barden",
      email: "maria@example.com",
      category: "Soft Rock",
      phone: "+1 234 567 890",
      lastQuotationAt: "1977-02-02",
      status: "active",
      TotalQuotations: 12,
      incoming: 45,
      image: "rumours",
      price: 40,
      sold: 15,
      priceIncrease: 5, // in percentage
      variants: 3,
      variantDetails: [
        {
          title: "100000001",
          status: "active",
          quantity: 4,
          dateCreated: "2024-01-01",
          dateSubmitted: "2024-01-02",
          format: "LP, Album, Picture Disc, Reissue",
          label: "Warner Records",
          cat: "RPD1 3010",
          country: "Worldwide",
          year: "2024",
        },
        {
          title: "100000002",
          status: "active",
          quantity: 6,
          dateCreated: "2024-01-01",
          dateSubmitted: "2024-01-02",
          format: "Blu-Ray, Album, Reissue, Dolby Atoms",
          label: "Warner Records",
          cat: "BA2 3010",
          country: "Worldwide",
          year: "2024",
        }
        ,
        {
          title: "100000003",
          status: "paused",
          quantity: 6,
          dateCreated: "2024-01-01",
          dateSubmitted: "2024-01-02",
          format: "Blu-Ray, Album, Reissue, Dolby Atoms",
          label: "Warner Records",
          cat: "BA2 3010",
          country: "Worldwide",
          year: "2024",
        }
        ,
        {
          title: "100000004",
          status: "outOfStock",
          quantity: 6,
          dateCreated: "2024-01-01",
          dateSubmitted: "2024-01-02",
          format: "Blu-Ray, Album, Reissue, Dolby Atoms",
          label: "Warner Records",
          cat: "BA2 3010",
          country: "Worldwide",
          year: "2024",
        }
      ],
    },
    {
      product: "Roberto Xavier",
      email: "Adele@gmail.com",
      category: "Pop",
      lastQuotationAt: "1977-02-02",
      phone: "+1 234 567 890",
      status: "draft",
      available: 0,
      incoming: 0,
      image: "futurenostalgia",
      price: 29,
      sold: 5,
      priceIncrease: 10,
      variants: 1,
      variantDetails: [
        {
          title: "Future Nostalgia",
          quantity: 0,
          dateCreated: "2024-01-01",
          dateSubmitted: "2024-01-02",
          format: "LP, Limited Edition, Magenta",
          label: "Warner Records",
          cat: "5054197954467",
          country: "Worldwide",
          year: "2024",
        },
      ],
    },
    {
      product: "Dougles Smith",
      email: "Adele@gmail.com",
      category: "Synth-pop",
      lastQuotationAt: "1977-02-02",
      phone: "+1 234 567 890",
      status: "active",
      available: 25,
      incoming: 0,
      image: "actually",
      price: 25,
      sold: 7,
      priceIncrease: 10,
      variants: 2,
      variantDetails: [
        {
          title: "Actually",
          quantity: 13,
          format: "LP, Album, Reissue, 180 Gram",
          label: "Parlophone",
          cat: "0190295832612",
          country: "USA & Europe",
          year: "2018",
        },
        {
          title: "Actually / Further Listening 1987-1988",
          quantity: 12,
          format: "CD, Album, Compilation; All Media, Reissue, Remastered",
          label: "Warner Records",
          cat: "01902958262222",
          country: "Europe",
          year: "2018",
        },
      ],
    },
    {
      product: "Baseden Smith",
      email: "amy@example.com",
      category: "Rhythm & Blues",
      lastQuotationAt: "1977-02-02",
      phone: "+1 234 567 890",
      status: "paused",
      available: 3,
      incoming: 19,
      image: "backtoblack",
      price: 33,
      sold: 39,
      priceIncrease: 5,
      variants: 4,
      variantDetails: [
        {
          title: "Back to Black",
          quantity: 1,
          format: "CD, Album, Enhanced",
          label: "Island Records Group",
          cat: "171 304-1",
          country: "UK",
          year: "2006",
        },
        {
          title: "Back to Black The Album Remixes",
          quantity: 0,
          format: "2×CD, Promo",
          label: "Island Records Ltd",
          cat: "AMYCDPRO15",
          country: "Europe",
          year: "2007",
        },
        {
          title: "Back to Black",
          quantity: 0,
          format: "LP, Album, Picture Disc, Reissue",
          label: "Island Records",
          cat: "3579647",
          country: "Europe",
          year: "2023",
        },
        {
          title: "Back to Black",
          quantity: 4,
          format: "LP, Album, Limited Edition, Reissue, Pink",
          label: "Republic Records",
          cat: "B0030246-01 ST01",
          country: "US",
          year: "2024",
        },
      ],
    },
    {
      product: "In A Dream",
      email: "sivan@example.com",
      category: "Pop",
      lastQuotationAt: "1977-02-02",
      phone: "+1 234 567 890",
      status: "draft",
      available: 0,
      incoming: 0,
      image: "inadream",
      price: 35,
      sold: 10,
      priceIncrease: 30,
      variants: 2,
      variantDetails: [
        {
          title: "In A Dream",
          available: 0,
          format: "CD, EP",
          label: "Capitol Records",
          cat: "DR3AM01",
          country: "US",
          year: "2020",
        },
        {
          title: "In A Dream",
          available: 0,
          format: "LP, EP, Blue Mist",
          label: "EMI",
          cat: "DR3AM02",
          country: "Europe",
          year: "2020",
        },
      ],
    },
    {
      product: "21",
      email: "Adele@gmail.com",
      category: "Pop",
      lastQuotationAt: "1977-02-02",
      phone: "+1 234 567 890",
      status: "active",
      available: 5,
      incoming: 10,
      image: "21",
      price: 28,
      sold: 4,
      priceIncrease: 12,
      variants: 2,
      variantDetails: [
        {
          title: "21",
          available: 1,
          format: "LP, Album, Stereo",
          label: "XL Recordings",
          cat: "XLLP 520",
          country: "Europe",
          year: "2011",
        },
        {
          title: "21",
          available: 4,
          format: "CD, Album, Limited Edition",
          label: "XL Recordings",
          cat: "XLLP 520 E",
          country: "Europe",
          year: "2011",
        },
      ],
    },


    {
      product: "Discovery",
      artist: "Daft Punk",
      category: "Electronic",
      year: "2001",
      status: "paused",
      available: 7,
      incoming: 0,
      image: "discovery",
      price: 20,
      sold: 2,
      priceIncrease: 5,
      variants: 3,
      variantDetails: [
        {
          title: "Discovery",
          available: 7,
          format: "2×LP, Album, Reissue, Gatefold",
          label: "ADA",
          cat: "0190296617164",
          country: "Europe",
          year: "2023",
        },
        {
          title: "Discovery",
          available: 0,
          format: "2×LP, Album, Reissue, Gatefold",
          label: "ADA",
          cat: "0190296617164",
          country: "USA & Europe",
          year: "2021",
        },
        {
          title: "Discovery",
          available: 0,
          format: "2×LP, Album, Reissue",
          label: "Parlophone",
          cat: "7243 8496061 2",
          country: "Europe",
          year: "2018",
        },
      ],
    },


  ];
  return data;
}
