export function getData() {
  const data = [
    {
      quotationID: "Q-10001",
      quotationDate: "2024-05-01",
      customerID: "C-001",
      customerName: "Maria Barden",
      email: "maria@example.com",
      category: "Soft Rock",
      phone: "+1 234 567 890",
      lastQuotationAt: "1977-02-02",
      status: "active",
      TotalQuotations: 12,
      incoming: 45,
      image: "rumours",
      price: 40,
      sold: 15,
      priceIncrease: 5,
      variants: 3,
    },
    {
      quotationID: "Q-10002",
      quotationDate: "2024-05-03",
      customerID: "C-001",
      customerName: "Maria Barden",
      email: "maria@example.com",
      category: "Soft Rock",
      phone: "+1 234 567 890",
      lastQuotationAt: "1977-02-03",
      status: "draft",
      TotalQuotations: 12,
      incoming: 10,
      image: "rumours",
      price: 38,
      sold: 3,
      priceIncrease: 3,
      variants: 1,
    },
    {
      quotationID: "Q-10003",
      quotationDate: "2024-05-02",
      customerID: "C-002",
      customerName: "Roberto Xavier",
      email: "Adele@gmail.com",
      category: "Pop",
      lastQuotationAt: "1977-02-02",
      phone: "+1 234 567 890",
      status: "draft",
      available: 0,
      incoming: 0,
      image: "futurenostalgia",
      price: 29,
      sold: 5,
      priceIncrease: 10,
      variants: 1,
    },
    {
      quotationID: "Q-10004",
      quotationDate: "2024-05-04",
      customerID: "C-003",
      customerName: "Dougles Smith",
      email: "Adele@gmail.com",
      category: "Synth-pop",
      lastQuotationAt: "1977-02-02",
      phone: "+1 234 567 890",
      status: "active",
      available: 25,
      incoming: 0,
      image: "actually",
      price: 25,
      sold: 7,
      priceIncrease: 10,
      variants: 2,
    },
    {
      product: "Baseden Smith",
      email: "amy@example.com",
      category: "Rhythm & Blues",
      lastQuotationAt: "1977-02-02",
      phone: "+1 234 567 890",
      status: "paused",
      available: 3,
      incoming: 19,
      image: "backtoblack",
      price: 33,
      sold: 39,
      priceIncrease: 5,
      variants: 4,
    },
    {
      product: "In A Dream",
      email: "sivan@example.com",
      category: "Pop",
      lastQuotationAt: "1977-02-02",
      phone: "+1 234 567 890",
      status: "draft",
      available: 0,
      incoming: 0,
      image: "inadream",
      price: 35,
      sold: 10,
      priceIncrease: 30,
      variants: 2,
    },
    {
      product: "21",
      email: "Adele@gmail.com",
      category: "Pop",
      lastQuotationAt: "1977-02-02",
      phone: "+1 234 567 890",
      status: "active",
      available: 5,
      incoming: 10,
      image: "21",
      price: 28,
      sold: 4,
      priceIncrease: 12,
      variants: 2,
    },
    {
      product: "Discovery",
      artist: "Daft Punk",
      category: "Electronic",
      year: "2001",
      status: "paused",
      available: 7,
      incoming: 0,
      image: "discovery",
      price: 20,
      sold: 2,
      priceIncrease: 5,
      variants: 3,
    },
  ];
  return data;
}
