// Mock data for the Ecommerce demo
export const getData = () => {
  return [
    {
      product: "Dreams of You",
      sku: "DOY-1978-01",
      artist: "David Nearing",
      category: "Music",
      subcategory: "Soft Rock",
      launchYear: "1978-01-01",
      status: "active",
      isDigital: false,
      price: 32,
      cost: 20,
      margin: 37.5, // derived
      priceIncrease: 5,
      availableTotal: 28,
      incomingTotal: 35,
      availableUS: 8,
      availableEU: 12,
      availableAsia: 8,
      warehousePrimary: "EU-Central",
      soldTotal: 45, // sum of monthlySales.sold
      soldUS: 15,
      soldEU: 20,
      soldAsia: 10,
      revenueTotal: 1440, // sum of monthly revenues
      revenueTrend: [100, 120, 80, 150, 90, 110, 200, 180, 140, 130, 160, 180],
      avgRating: 4.2,
      reviewCount: 120,
      variantsCount: 3,
      variantDetails: [
        {
          title: "Dreams of You",
          available: 5,
          format: "LP, Album, Reissue",
          label: "Amberline Records",
          cat: "ARL1978-01",
          country: "Worldwide",
          year: "2024",
        },
        {
          title: "Dreams of You",
          available: 3,
          format: "CD, Album, Remastered",
          label: "Amberline Records",
          cat: "ARCD-78X",
          country: "Europe",
          year: "2024",
        },
      ],
      image: "dreamsofyou.webp",
      monthlySales: [
        { month: "Jan", sold: 3, revenue: 96 },
        { month: "Feb", sold: 4, revenue: 128 },
        { month: "Mar", sold: 2, revenue: 64 },
        { month: "Apr", sold: 5, revenue: 160 },
        { month: "May", sold: 3, revenue: 96 },
        { month: "Jun", sold: 3, revenue: 96 },
        { month: "Jul", sold: 6, revenue: 192 },
        { month: "Aug", sold: 5, revenue: 160 },
        { month: "Sep", sold: 4, revenue: 128 },
        { month: "Oct", sold: 4, revenue: 128 },
        { month: "Nov", sold: 5, revenue: 160 },
        { month: "Dec", sold: 6, revenue: 192 },
      ],
      soldJan: 3,
      soldFeb: 4,
      soldMar: 2,
      soldApr: 5,
      soldMay: 3,
      soldJun: 3,
      soldJul: 6,
      soldAug: 5,
      soldSep: 4,
      soldOct: 4,
      soldNov: 5,
      soldDec: 6,
      revenueJan: 96,
      revenueFeb: 128,
      revenueMar: 64,
      revenueApr: 160,
      revenueMay: 96,
      revenueJun: 96,
      revenueJul: 192,
      revenueAug: 160,
      revenueSep: 128,
      revenueOct: 128,
      revenueNov: 160,
      revenueDec: 192,
    },
    {
      product: "Echoes of Eternity",
      sku: "EOE-1985-02",
      artist: "Celestial Harmonies",
      category: "Music",
      subcategory: "Ambient",
      launchYear: "1985-02-15",
      status: "active",
      isDigital: true,
      price: 25,
      cost: 15,
      margin: 40, // derived
      priceIncrease: 3,
      availableTotal: 50,
      incomingTotal: 20,
      availableUS: 20,
      availableEU: 15,
      availableAsia: 15,
      warehousePrimary: "US-East",
      soldTotal: 60, // sum of monthlySales.sold
      soldUS: 25,
      soldEU: 20,
      soldAsia: 15,
      revenueTotal: 1500, // sum of monthly revenues
      revenueTrend: [120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230],
      avgRating: 4.8,
      reviewCount: 200,
      variantsCount: 2,
      variantDetails: [
        {
          title: "Echoes of Eternity",
          available: 10,
          format: "Digital Download",
          label: "Harmonic Waves",
          cat: "HW1985-02",
          country: "Worldwide",
          year: "2026",
        },
        {
          title: "Echoes of Eternity",
          available: 5,
          format: "Vinyl, Limited Edition",
          label: "Harmonic Waves",
          cat: "HW-VNL-85",
          country: "US",
          year: "2026",
        },
      ],
      image: "echoesofeternity.webp",
      monthlySales: [
        { month: "Jan", sold: 5, revenue: 125 },
        { month: "Feb", sold: 6, revenue: 150 },
        { month: "Mar", sold: 4, revenue: 100 },
        { month: "Apr", sold: 7, revenue: 175 },
        { month: "May", sold: 5, revenue: 125 },
        { month: "Jun", sold: 6, revenue: 150 },
        { month: "Jul", sold: 8, revenue: 200 },
        { month: "Aug", sold: 7, revenue: 175 },
        { month: "Sep", sold: 6, revenue: 150 },
        { month: "Oct", sold: 6, revenue: 150 },
        { month: "Nov", sold: 7, revenue: 175 },
        { month: "Dec", sold: 8, revenue: 200 },
      ],
      soldJan: 5,
      soldFeb: 6,
      soldMar: 4,
      soldApr: 7,
      soldMay: 5,
      soldJun: 6,
      soldJul: 8,
      soldAug: 7,
      soldSep: 6,
      soldOct: 6,
      soldNov: 7,
      soldDec: 8,
      revenueJan: 125,
      revenueFeb: 150,
      revenueMar: 100,
      revenueApr: 175,
      revenueMay: 125,
      revenueJun: 150,
      revenueJul: 200,
      revenueAug: 175,
      revenueSep: 150,
      revenueOct: 150,
      revenueNov: 175,
      revenueDec: 200,
    },
    {
      product: "Rhythms of the Night",
      sku: "RON-1990-03",
      artist: "Nocturnal Groove",
      category: "Music",
      subcategory: "Jazz",
      launchYear: "1990-03-10",
      status: "active",
      isDigital: false,
      price: 28,
      cost: 18,
      margin: 35.71, // derived
      priceIncrease: 4,
      availableTotal: 40,
      incomingTotal: 30,
      availableUS: 15,
      availableEU: 15,
      availableAsia: 10,
      warehousePrimary: "EU-West",
      soldTotal: 50, // sum of monthlySales.sold
      soldUS: 20,
      soldEU: 15,
      soldAsia: 15,
      revenueTotal: 1400, // sum of monthly revenues
      revenueTrend: [110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165],
      avgRating: 4.5,
      reviewCount: 180,
      variantsCount: 1,
      variantDetails: [
        {
          title: "Rhythms of the Night",
          available: 20,
          format: "LP, Album",
          label: "Midnight Records",
          cat: "MR1990-03",
          country: "Worldwide",
          year: "2025",
        },
      ],
      image: "rhythmsofthenight.webp",
      monthlySales: [
        { month: "Jan", sold: 4, revenue: 112 },
        { month: "Feb", sold: 5, revenue: 140 },
        { month: "Mar", sold: 3, revenue: 84 },
        { month: "Apr", sold: 6, revenue: 168 },
        { month: "May", sold: 4, revenue: 112 },
        { month: "Jun", sold: 4, revenue: 112 },
        { month: "Jul", sold: 7, revenue: 196 },
        { month: "Aug", sold: 6, revenue: 168 },
        { month: "Sep", sold: 5, revenue: 140 },
        { month: "Oct", sold: 5, revenue: 140 },
        { month: "Nov", sold: 6, revenue: 168 },
        { month: "Dec", sold: 7, revenue: 196 },
      ],
      soldJan: 4,
      soldFeb: 5,
      soldMar: 3,
      soldApr: 6,
      soldMay: 4,
      soldJun: 4,
      soldJul: 7,
      soldAug: 6,
      soldSep: 5,
      soldOct: 5,
      soldNov: 6,
      soldDec: 7,
      revenueJan: 112,
      revenueFeb: 140,
      revenueMar: 84,
      revenueApr: 168,
      revenueMay: 112,
      revenueJun: 112,
      revenueJul: 196,
      revenueAug: 168,
      revenueSep: 140,
      revenueOct: 140,
      revenueNov: 168,
      revenueDec: 196,
    },
    {
      product: "Visions of the Future",
      sku: "VTF-2000-04",
      artist: "Future Sounds",
      category: "Music",
      subcategory: "Electronic",
      launchYear: "2000-04-20",
      status: "active",
      isDigital: true,
      price: 30,
      cost: 22,
      margin: 26.67, // derived
      priceIncrease: 6,
      availableTotal: 35,
      incomingTotal: 25,
      availableUS: 10,
      availableEU: 15,
      availableAsia: 10,
      warehousePrimary: "EU-North",
      soldTotal: 55, // sum of monthlySales.sold
      soldUS: 18,
      soldEU: 20,
      soldAsia: 17,
      revenueTotal: 1650, // sum of monthly revenues
      revenueTrend: [130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240],
      avgRating: 4.9,
      reviewCount: 250,
      variantsCount: 3,
      variantDetails: [
        {
          title: "Visions of the Future",
          available: 15,
          format: "Digital Download",
          label: "Soundscapes",
          cat: "SS2000-04",
          country: "Worldwide",
          year: "2027",
        },
        {
          title: "Visions of the Future",
          available: 10,
          format: "CD, Album",
          label: "Soundscapes",
          cat: "SS-CD-00",
          country: "Europe",
          year: "2027",
        },
        {
          title: "Visions of the Future",
          available: 5,
          format: "Vinyl, 12\", Single",
          label: "Soundscapes",
          cat: "SS-VNL-00",
          country: "US",
          year: "2027",
        },
      ],
      image: "visionsofthefuture.webp",
      monthlySales: [
        { month: "Jan", sold: 6, revenue: 180 },
        { month: "Feb", sold: 7, revenue: 210 },
        { month: "Mar", sold: 5, revenue: 150 },
        { month: "Apr", sold: 8, revenue: 240 },
        { month: "May", sold: 6, revenue: 180 },
        { month: "Jun", sold: 7, revenue: 210 },
        { month: "Jul", sold: 9, revenue: 270 },
        { month: "Aug", sold: 8, revenue: 240 },
        { month: "Sep", sold: 7, revenue: 210 },
        { month: "Oct", sold: 7, revenue: 210 },
        { month: "Nov", sold: 8, revenue: 240 },
        { month: "Dec", sold: 9, revenue: 270 },
      ],
      soldJan: 6,
      soldFeb: 7,
      soldMar: 5,
      soldApr: 8,
      soldMay: 6,
      soldJun: 7,
      soldJul: 9,
      soldAug: 8,
      soldSep: 7,
      soldOct: 7,
      soldNov: 8,
      soldDec: 9,
      revenueJan: 180,
      revenueFeb: 210,
      revenueMar: 150,
      revenueApr: 240,
      revenueMay: 180,
      revenueJun: 210,
      revenueJul: 270,
      revenueAug: 240,
      revenueSep: 210,
      revenueOct: 210,
      revenueNov: 240,
      revenueDec: 270,
    },
    {
      product: "Legends Never Die",
      sku: "LND-2010-05",
      artist: "Eternal Bards",
      category: "Music",
      subcategory: "Classical",
      launchYear: "2010-05-30",
      status: "active",
      isDigital: false,
      price: 35,
      cost: 25,
      margin: 28.57, // derived
      priceIncrease: 7,
      availableTotal: 20,
      incomingTotal: 10,
      availableUS: 5,
      availableEU: 10,
      availableAsia: 5,
      warehousePrimary: "EU-South",
      soldTotal: 30, // sum of monthlySales.sold
      soldUS: 10,
      soldEU: 12,
      soldAsia: 8,
      revenueTotal: 1050, // sum of monthly revenues
      revenueTrend: [140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250],
      avgRating: 4.7,
      reviewCount: 220,
      variantsCount: 2,
      variantDetails: [
        {
          title: "Legends Never Die",
          available: 10,
          format: "LP, Album",
          label: "Timeless Records",
          cat: "TR2010-05",
          country: "Worldwide",
          year: "2028",
        },
        {
          title: "Legends Never Die",
          available: 5,
          format: "CD, Album, Deluxe Edition",
          label: "Timeless Records",
          cat: "TR-CD-10",
          country: "Europe",
          year: "2028",
        },
      ],
      image: "legendsneverdie.webp",
      monthlySales: [
        { month: "Jan", sold: 2, revenue: 70 },
        { month: "Feb", sold: 3, revenue: 105 },
        { month: "Mar", sold: 2, revenue: 70 },
        { month: "Apr", sold: 4, revenue: 140 },
        { month: "May", sold: 2, revenue: 70 },
        { month: "Jun", sold: 3, revenue: 105 },
        { month: "Jul", sold: 5, revenue: 175 },
        { month: "Aug", sold: 4, revenue: 140 },
        { month: "Sep", sold: 3, revenue: 105 },
        { month: "Oct", sold: 3, revenue: 105 },
        { month: "Nov", sold: 4, revenue: 140 },
        { month: "Dec", sold: 5, revenue: 175 },
      ],
      soldJan: 2,
      soldFeb: 3,
      soldMar: 2,
      soldApr: 4,
      soldMay: 2,
      soldJun: 3,
      soldJul: 5,
      soldAug: 4,
      soldSep: 3,
      soldOct: 3,
      soldNov: 4,
      soldDec: 5,
      revenueJan: 70,
      revenueFeb: 105,
      revenueMar: 70,
      revenueApr: 140,
      revenueMay: 70,
      revenueJun: 105,
      revenueJul: 175,
      revenueAug: 140,
      revenueSep: 105,
      revenueOct: 105,
      revenueNov: 140,
      revenueDec: 175,
    },
    {
      product: "The Sound of Silence",
      sku: "SOS-2020-06",
      artist: "Whispers of the Void",
      category: "Music",
      subcategory: "Experimental",
      launchYear: "2020-06-15",
      status: "active",
      isDigital: true,
      price: 40,
      cost: 30,
      margin: 25, // derived
      priceIncrease: 8,
      availableTotal: 10,
      incomingTotal: 5,
      availableUS: 2,
      availableEU: 3,
      availableAsia: 5,
      warehousePrimary: "Asia-South",
      soldTotal: 20, // sum of monthlySales.sold
      soldUS: 5,
      soldEU: 8,
      soldAsia: 7,
      revenueTotal: 800, // sum of monthly revenues
      revenueTrend: [200, 220, 240, 260, 280, 300, 320, 340, 360, 380, 400, 420],
      avgRating: 4.6,
      reviewCount: 190,
      variantsCount: 1,
      variantDetails: [
        {
          title: "The Sound of Silence",
          available: 5,
          format: "Digital Album",
          label: "Silence Records",
          cat: "SR2020-06",
          country: "Worldwide",
          year: "2029",
        },
      ],
      image: "thesoundofsilence.webp",
      monthlySales: [
        { month: "Jan", sold: 1, revenue: 40 },
        { month: "Feb", sold: 2, revenue: 80 },
        { month: "Mar", sold: 1, revenue: 40 },
        { month: "Apr", sold: 3, revenue: 120 },
        { month: "May", sold: 1, revenue: 40 },
        { month: "Jun", sold: 2, revenue: 80 },
        { month: "Jul", sold: 4, revenue: 160 },
        { month: "Aug", sold: 3, revenue: 120 },
        { month: "Sep", sold: 2, revenue: 80 },
        { month: "Oct", sold: 2, revenue: 80 },
        { month: "Nov", sold: 3, revenue: 120 },
        { month: "Dec", sold: 4, revenue: 160 },
      ],
      soldJan: 1,
      soldFeb: 2,
      soldMar: 1,
      soldApr: 3,
      soldMay: 1,
      soldJun: 2,
      soldJul: 4,
      soldAug: 3,
      soldSep: 2,
      soldOct: 2,
      soldNov: 3,
      soldDec: 4,
      revenueJan: 40,
      revenueFeb: 80,
      revenueMar: 40,
      revenueApr: 120,
      revenueMay: 40,
      revenueJun: 80,
      revenueJul: 160,
      revenueAug: 120,
      revenueSep: 80,
      revenueOct: 80,
      revenueNov: 120,
      revenueDec: 160,
    },
    {
      product: "Awakening",
      sku: "AWK-2030-07",
      artist: "New Dawn",
      category: "Music",
      subcategory: "New Age",
      launchYear: "2030-07-01",
      status: "active",
      isDigital: true,
      price: 45,
      cost: 35,
      margin: 22.22, // derived
      priceIncrease: 9,
      availableTotal: 15,
      incomingTotal: 10,
      availableUS: 5,
      availableEU: 5,
      availableAsia: 5,
      warehousePrimary: "Asia-East",
      soldTotal: 25, // sum of monthlySales.sold
      soldUS: 10,
      soldEU: 8,
      soldAsia: 7,
      revenueTotal: 1125, // sum of monthly revenues
      revenueTrend: [250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360],
      avgRating: 4.9,
      reviewCount: 210,
      variantsCount: 2,
      variantDetails: [
        {
          title: "Awakening",
          available: 10,
          format: "Digital Album",
          label: "Dawn Records",
          cat: "DR2030-07",
          country: "Worldwide",
          year: "2031",
        },
        {
          title: "Awakening",
          available: 5,
          format: "CD, Album",
          label: "Dawn Records",
          cat: "DR-CD-30",
          country: "Europe",
          year: "2031",
        },
      ],
      image: "awakening.webp",
      monthlySales: [
        { month: "Jan", sold: 3, revenue: 135 },
        { month: "Feb", sold: 4, revenue: 180 },
        { month: "Mar", sold: 3, revenue: 135 },
        { month: "Apr", sold: 5, revenue: 225 },
        { month: "May", sold: 3, revenue: 135 },
        { month: "Jun", sold: 4, revenue: 180 },
        { month: "Jul", sold: 6, revenue: 270 },
        { month: "Aug", sold: 5, revenue: 225 },
        { month: "Sep", sold: 4, revenue: 180 },
        { month: "Oct", sold: 4, revenue: 180 },
        { month: "Nov", sold: 5, revenue: 225 },
        { month: "Dec", sold: 6, revenue: 270 },
      ],
      soldJan: 3,
      soldFeb: 4,
      soldMar: 3,
      soldApr: 5,
      soldMay: 3,
      soldJun: 4,
      soldJul: 6,
      soldAug: 5,
      soldSep: 4,
      soldOct: 4,
      soldNov: 5,
      soldDec: 6,
      revenueJan: 135,
      revenueFeb: 180,
      revenueMar: 135,
      revenueApr: 225,
      revenueMay: 135,
      revenueJun: 180,
      revenueJul: 270,
      revenueAug: 225,
      revenueSep: 180,
      revenueOct: 180,
      revenueNov: 225,
      revenueDec: 270,
    },
    {
      product: "Beyond the Horizon",
      sku: "BTH-2040-08",
      artist: "Limitless",
      category: "Music",
      subcategory: "Rock",
      launchYear: "2040-08-20",
      status: "active",
      isDigital: false,
      price: 50,
      cost: 40,
      margin: 20, // derived
      priceIncrease: 10,
      availableTotal: 5,
      incomingTotal: 5,
      availableUS: 2,
      availableEU: 2,
      availableAsia: 1,
      warehousePrimary: "US-West",
      soldTotal: 10, // sum of monthlySales.sold
      soldUS: 4,
      soldEU: 3,
      soldAsia: 3,
      revenueTotal: 500, // sum of monthly revenues
      revenueTrend: [300, 320, 340, 360, 380, 400, 420, 440, 460, 480, 500, 520],
      avgRating: 4.8,
      reviewCount: 230,
      variantsCount: 1,
      variantDetails: [
        {
          title: "Beyond the Horizon",
          available: 5,
          format: "LP, Album",
          label: "Pinnacle Records",
          cat: "PR2040-08",
          country: "Worldwide",
          year: "2041",
        },
      ],
      image: "beyondthehorizon.webp",
      monthlySales: [
        { month: "Jan", sold: 1, revenue: 50 },
        { month: "Feb", sold: 1, revenue: 50 },
        { month: "Mar", sold: 1, revenue: 50 },
        { month: "Apr", sold: 2, revenue: 100 },
        { month: "May", sold: 1, revenue: 50 },
        { month: "Jun", sold: 1, revenue: 50 },
        { month: "Jul", sold: 2, revenue: 100 },
        { month: "Aug", sold: 2, revenue: 100 },
        { month: "Sep", sold: 1, revenue: 50 },
        { month: "Oct", sold: 1, revenue: 50 },
        { month: "Nov", sold: 2, revenue: 100 },
        { month: "Dec", sold: 2, revenue: 100 },
      ],
      soldJan: 1,
      soldFeb: 1,
      soldMar: 1,
      soldApr: 2,
      soldMay: 1,
      soldJun: 1,
      soldJul: 2,
      soldAug: 2,
      soldSep: 1,
      soldOct: 1,
      soldNov: 2,
      soldDec: 2,
      revenueJan: 50,
      revenueFeb: 50,
      revenueMar: 50,
      revenueApr: 100,
      revenueMay: 50,
      revenueJun: 50,
      revenueJul: 100,
      revenueAug: 100,
      revenueSep: 50,
      revenueOct: 50,
      revenueNov: 100,
      revenueDec: 100,
    },
    {
      product: "The Best of Times",
      sku: "BOT-2050-09",
      artist: "Timeless Band",
      category: "Music",
      subcategory: "Rock",
      launchYear: "2050-09-10",
      status: "active",
      isDigital: true,
      price: 55,
      cost: 45,
      margin: 18.18, // derived
      priceIncrease: 11,
      availableTotal: 8,
      incomingTotal: 4,
      availableUS: 3,
      availableEU: 3,
      availableAsia: 2,
      warehousePrimary: "Asia-Central",
      soldTotal: 12, // sum of monthlySales.sold
      soldUS: 5,
      soldEU: 4,
      soldAsia: 3,
      revenueTotal: 660, // sum of monthly revenues
      revenueTrend: [350, 370, 390, 410, 430, 450, 470, 490, 510, 530, 550, 570],
      avgRating: 4.7,
      reviewCount: 240,
      variantsCount: 2,
      variantDetails: [
        {
          title: "The Best of Times",
          available: 5,
          format: "Digital Album",
          label: "Best Records",
          cat: "BR2050-09",
          country: "Worldwide",
          year: "2051",
        },
        {
          title: "The Best of Times",
          available: 3,
          format: "CD, Album",
          label: "Best Records",
          cat: "BR-CD-50",
          country: "Europe",
          year: "2051",
        },
      ],
      image: "thebestoftimes.webp",
      monthlySales: [
        { month: "Jan", sold: 2, revenue: 110 },
        { month: "Feb", sold: 2, revenue: 110 },
        { month: "Mar", sold: 2, revenue: 110 },
        { month: "Apr", sold: 3, revenue: 165 },
        { month: "May", sold: 2, revenue: 110 },
        { month: "Jun", sold: 2, revenue: 110 },
        { month: "Jul", sold: 3, revenue: 165 },
        { month: "Aug", sold: 3, revenue: 165 },
        { month: "Sep", sold: 2, revenue: 110 },
        { month: "Oct", sold: 2, revenue: 110 },
        { month: "Nov", sold: 3, revenue: 165 },
        { month: "Dec", sold: 3, revenue: 165 },
      ],
      soldJan: 2,
      soldFeb: 2,
      soldMar: 2,
      soldApr: 3,
      soldMay: 2,
      soldJun: 2,
      soldJul: 3,
      soldAug: 3,
      soldSep: 2,
      soldOct: 2,
      soldNov: 3,
      soldDec: 3,
      revenueJan: 110,
      revenueFeb: 110,
      revenueMar: 110,
      revenueApr: 165,
      revenueMay: 110,
      revenueJun: 110,
      revenueJul: 165,
      revenueAug: 165,
      revenueSep: 110,
      revenueOct: 110,
      revenueNov: 165,
      revenueDec: 165,
    },
    {
      product: "Chasing Dreams",
      sku: "CD-2060-10",
      artist: "Dreamcatchers",
      category: "Music",
      subcategory: "Pop",
      launchYear: "2060-10-05",
      status: "active",
      isDigital: false,
      price: 60,
      cost: 50,
      margin: 16.67, // derived
      priceIncrease: 12,
      availableTotal: 6,
      incomingTotal: 3,
      availableUS: 2,
      availableEU: 2,
      availableAsia: 2,
      warehousePrimary: "US-South",
      soldTotal: 8, // sum of monthlySales.sold
      soldUS: 3,
      soldEU: 2,
      soldAsia: 3,
      revenueTotal: 480, // sum of monthly revenues
      revenueTrend: [400, 420, 440, 460, 480, 500, 520, 540, 560, 580, 600, 620],
      avgRating: 4.6,
      reviewCount: 210,
      variantsCount: 1,
      variantDetails: [
        {
          title: "Chasing Dreams",
          available: 6,
          format: "LP, Album",
          label: "Visionary Records",
          cat: "VR2060-10",
          country: "Worldwide",
          year: "2061",
        },
      ],
      image: "chasingdreams.webp",
      monthlySales: [
        { month: "Jan", sold: 2, revenue: 120 },
        { month: "Feb", sold: 2, revenue: 120 },
        { month: "Mar", sold: 2, revenue: 120 },
        { month: "Apr", sold: 3, revenue: 180 },
        { month: "May", sold: 2, revenue: 120 },
        { month: "Jun", sold: 2, revenue: 120 },
        { month: "Jul", sold: 3, revenue: 180 },
        { month: "Aug", sold: 3, revenue: 180 },
        { month: "Sep", sold: 2, revenue: 120 },
        { month: "Oct", sold: 2, revenue: 120 },
        { month: "Nov", sold: 3, revenue: 180 },
        { month: "Dec", sold: 3, revenue: 180 },
      ],
      soldJan: 2,
      soldFeb: 2,
      soldMar: 2,
      soldApr: 3,
      soldMay: 2,
      soldJun: 2,
      soldJul: 3,
      soldAug: 3,
      soldSep: 2,
      soldOct: 2,
      soldNov: 3,
      soldDec: 3,
      revenueJan: 120,
      revenueFeb: 120,
      revenueMar: 120,
      revenueApr: 180,
      revenueMay: 120,
      revenueJun: 120,
      revenueJul: 180,
      revenueAug: 180,
      revenueSep: 120,
      revenueOct: 120,
      revenueNov: 180,
      revenueDec: 180,
    },
    {
      product: "Timeless Classics",
      sku: "TC-2070-11",
      artist: "Classic Band",
      category: "Music",
      subcategory: "Classical",
      launchYear: "2070-11-15",
      status: "active",
      isDigital: true,
      price: 65,
      cost: 55,
      margin: 15.38, // derived
      priceIncrease: 13,
      availableTotal: 4,
      incomingTotal: 2,
      availableUS: 1,
      availableEU: 2,
      availableAsia: 1,
      warehousePrimary: "EU-West",
      soldTotal: 6, // sum of monthlySales.sold
      soldUS: 2,
      soldEU: 2,
      soldAsia: 2,
      revenueTotal: 390, // sum of monthly revenues
      revenueTrend: [450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550, 560],
      avgRating: 4.9,
      reviewCount: 260,
      variantsCount: 2,
      variantDetails: [
        {
          title: "Timeless Classics",
          available: 4,
          format: "Digital Album",
          label: "Eternal Records",
          cat: "ER2070-11",
          country: "Worldwide",
          year: "2071",
        },
        {
          title: "Timeless Classics",
          available: 2,
          format: "CD, Album",
          label: "Eternal Records",
          cat: "ER-CD-70",
          country: "Europe",
          year: "2071",
        },
      ],
      image: "timelessclassics.webp",
      monthlySales: [
        { month: "Jan", sold: 1, revenue: 65 },
        { month: "Feb", sold: 1, revenue: 65 },
        { month: "Mar", sold: 1, revenue: 65 },
        { month: "Apr", sold: 2, revenue: 130 },
        { month: "May", sold: 1, revenue: 65 },
        { month: "Jun", sold: 1, revenue: 65 },
        { month: "Jul", sold: 2, revenue: 130 },
        { month: "Aug", sold: 2, revenue: 130 },
        { month: "Sep", sold: 1, revenue: 65 },
        { month: "Oct", sold: 1, revenue: 65 },
        { month: "Nov", sold: 2, revenue: 130 },
        { month: "Dec", sold: 2, revenue: 130 },
      ],
      soldJan: 1,
      soldFeb: 1,
      soldMar: 1,
      soldApr: 2,
      soldMay: 1,
      soldJun: 1,
      soldJul: 2,
      soldAug: 2,
      soldSep: 1,
      soldOct: 1,
      soldNov: 2,
      soldDec: 2,
      revenueJan: 65,
      revenueFeb: 65,
      revenueMar: 65,
      revenueApr: 130,
      revenueMay: 65,
      revenueJun: 65,
      revenueJul: 130,
      revenueAug: 130,
      revenueSep: 65,
      revenueOct: 65,
      revenueNov: 130,
      revenueDec: 130,
    },
    {
      product: "The Greatest Hits",
      sku: "TGH-2080-12",
      artist: "Superstar",
      category: "Music",
      subcategory: "Pop",
      launchYear: "2080-12-01",
      status: "active",
      isDigital: false,
      price: 70,
      cost: 60,
      margin: 14.29, // derived
      priceIncrease: 14,
      availableTotal: 3,
      incomingTotal: 2,
      availableUS: 1,
      availableEU: 1,
      availableAsia: 1,
      warehousePrimary: "Asia-West",
      soldTotal: 4, // sum of monthlySales.sold
      soldUS: 1,
      soldEU: 2,
      soldAsia: 1,
      revenueTotal: 280, // sum of monthly revenues
      revenueTrend: [500, 520, 540, 560, 580, 600, 620, 640, 660, 680, 700, 720],
      avgRating: 4.8,
      reviewCount: 250,
      variantsCount: 1,
      variantDetails: [
        {
          title: "The Greatest Hits",
          available: 3,
          format: "LP, Album",
          label: "Hit Records",
          cat: "HR2080-12",
          country: "Worldwide",
          year: "2081",
        },
      ],
      image: "thegreatesthits.webp",
      monthlySales: [
        { month: "Jan", sold: 1, revenue: 70 },
        { month: "Feb", sold: 1, revenue: 70 },
        { month: "Mar", sold: 1, revenue: 70 },
        { month: "Apr", sold: 1, revenue: 70 },
        { month: "May", sold: 1, revenue: 70 },
        { month: "Jun", sold: 1, revenue: 70 },
        { month: "Jul", sold: 1, revenue: 70 },
        { month: "Aug", sold: 1, revenue: 70 },
        { month: "Sep", sold: 1, revenue: 70 },
        { month: "Oct", sold: 1, revenue: 70 },
        { month: "Nov", sold: 1, revenue: 70 },
        { month: "Dec", sold: 1, revenue: 70 },
      ],
      soldJan: 1,
      soldFeb: 1,
      soldMar: 1,
      soldApr: 1,
      soldMay: 1,
      soldJun: 1,
      soldJul: 1,
      soldAug: 1,
      soldSep: 1,
      soldOct: 1,
      soldNov: 1,
      soldDec: 1,
      revenueJan: 70,
      revenueFeb: 70,
      revenueMar: 70,
      revenueApr: 70,
      revenueMay: 70,
      revenueJun: 70,
      revenueJul: 70,
      revenueAug: 70,
      revenueSep: 70,
      revenueOct: 70,
      revenueNov: 70,
      revenueDec: 70,
    },
    {
      product: "The Ultimate Collection",
      sku: "TUC-2090-01",
      artist: "Various Artists",
      category: "Music",
      subcategory: "Compilation",
      launchYear: "2090-01-20",
      status: "active",
      isDigital: true,
      price: 75,
      cost: 65,
      margin: 13.33, // derived
      priceIncrease: 15,
      availableTotal: 2,
      incomingTotal: 1,
      availableUS: 1,
      availableEU: 1,
      availableAsia: 0,
      warehousePrimary: "EU-Central",
      soldTotal: 2, // sum of monthlySales.sold
      soldUS: 1,
      soldEU: 1,
      soldAsia: 0,
      revenueTotal: 150, // sum of monthly revenues
      revenueTrend: [600, 620, 640, 660, 680, 700, 720, 740, 760, 780, 800, 820],
      avgRating: 4.9,
      reviewCount: 300,
      variantsCount: 1,
      variantDetails: [
        {
          title: "The Ultimate Collection",
          available: 2,
          format: "Digital Album",
          label: "Various Labels",
          cat: "VL2090-01",
          country: "Worldwide",
          year: "2091",
        },
      ],
      image: "theultimatecollection.webp",
      monthlySales: [
        { month: "Jan", sold: 1, revenue: 75 },
        { month: "Feb", sold: 1, revenue: 75 },
        { month: "Mar", sold: 1, revenue: 75 },
        { month: "Apr", sold: 1, revenue: 75 },
        { month: "May", sold: 1, revenue: 75 },
        { month: "Jun", sold: 1, revenue: 75 },
        { month: "Jul", sold: 1, revenue: 75 },
        { month: "Aug", sold: 1, revenue: 75 },
        { month: "Sep", sold: 1, revenue: 75 },
        { month: "Oct", sold: 1, revenue: 75 },
        { month: "Nov", sold: 1, revenue: 75 },
        { month: "Dec", sold: 1, revenue: 75 },
      ],
      soldJan: 1,
      soldFeb: 1,
      soldMar: 1,
      soldApr: 1,
      soldMay: 1,
      soldJun: 1,
      soldJul: 1,
      soldAug: 1,
      soldSep: 1,
      soldOct: 1,
      soldNov: 1,
      soldDec: 1,
      revenueJan: 75,
      revenueFeb: 75,
      revenueMar: 75,
      revenueApr: 75,
      revenueMay: 75,
      revenueJun: 75,
      revenueJul: 75,
      revenueAug: 75,
      revenueSep: 75,
      revenueOct: 75,
      revenueNov: 75,
      revenueDec: 75,
    },
  ];
};
